openapi: 3.0.0
info:
  title: Temp API
  version: 1.0.0
  description: 데이터베이스에서 테이블 이름을 검색하는 API

paths:
  /temp:
    get:
      summary: 테이블 이름 가져오기
      description: 데이터베이스에서 테이블 이름 목록을 검색합니다
      responses:
        "200":
          description: 테이블 이름 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  tableNames:
                    type: array
                    items:
                      type: string
        "500":
          description: 오류 메시지
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
